
  name: playork
  version: '1.4.0'
  summary: playork,tools and games snap
  description: |
    Collection of some simple tools
  grade: stable
  confinement: strict

  parts:
    my-part:
      plugin: nil
  
